name: RunsafeInventories
main: no.runsafe.runsafeinventories.Plugin
version: 1.0.@BUILD@
authors: [Kruithne]
depend: []
description:
commands:
  wipeworld:
    description: Removes all database inventories for a world.
