name: RunsafeInventories
main: no.runsafe.runsafeinventories.Plugin
version: 1.0.@BUILD@
authors: [Kruithne]
description: Plugin for controlling inventories across worlds
commands:
  wipeworld:
    description: Removes all database inventories for a world.
  inventory:
    description: Inventory handling commands
    aliases: [inv]
